mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # 로그인 뷰는 따로 만들 필요없이 위 코드처럼 django.contrib.auth 앱의 LoginView를 사용하도록 설정했다.
    # 로그인은 common앱에 구현할거기떄문에 registion 디렉토리에 가지 않을거다.
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
# from pybo import views
# views안에 있는 함수들을 효율적으로 관리하기 위해
from pybo.views import base_views

#from pybo import views 너 대신에 위에 include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('pybo/', views.index),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    #로그인, 로그아웃을 위한 common을 등록
    # path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('', base_views.index, name='index'), # '/' 에 해당되는 path
]



#시작

mysite/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

from . import views

app_name = "pybo"
#pybo폴더가 하나이상일 경우 구분해주기 위함

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('<int:question_id>/', views.detail, name='detail'),
#     # path('<int:question_index>/', views.detail2),
#     # int:question_id >> 질문에 해당하는 번호
#     path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
#     path('question/create/', views.question_create, name='question_create'),
#     path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
#     path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
#     path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
#     path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    
# ]


urlpatterns = [
     # base_views.py
     path('',
          base_views.index, name='index'),
     path('<int:question_id>/',
          base_views.detail, name='detail'),

     # question_views.py
     path('question/create/',
          question_views.question_create, name='question_create'),
     path('question/modify/<int:question_id>/',
          question_views.question_modify, name='question_modify'),
     path('question/delete/<int:question_id>/',
          question_views.question_delete, name='question_delete'),

     # answer_views.py
     path('answer/create/<int:question_id>/',
          answer_views.answer_create, name='answer_create'),
     path('answer/modify/<int:answer_id>/',
          answer_views.answer_modify, name='answer_modify'),
     path('answer/delete/<int:answer_id>/',
          answer_views.answer_delete, name='answer_delete'),


     path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
     path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]



# 새로운 url을 여기서 등록
#

mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from ..models import Question




def index(request):
    page = request.GET.get('page', '1') #페이지
    kw = request.GET.get('kw', '')  # 검색어
    # page = request.GET.get('page', '1')은 http://localhost:8000/pybo/?page=1 
    # 처럼 GET 방식으로 호출된 URL에서 page값을 가져올 때 사용한다. 
    # 만약 http://localhost:8000/pybo/ 처럼 page값 없이 호출된 경우에는 디폴트로 1이라는 값을 설정한다.
    question_list = Question.objects.order_by('-create_date')
    #order_by('-create_date')  create_date의 역순으로

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
            # subject__icontains=kw의 의미는 제목에 kw 문자열이 포함되었는지를 의미한다.
            # 대소문자 가리지 않고 찾아준다.
        ).distinct()

    paginator = Paginator(question_list, 10) #페이지 하나당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    # 요청된 페이지(page)에 해당되는 페이징 객체(page_obj)를 생성했다. 이렇게 하면 장고 
    # 내부적으로는 데이터 전체를 조회하지 않고 해당 페이지의 데이터만 조회하도록 쿼리가 변경된다.

    context = {'question_list' : page_obj, 'page': page, 'kw': kw} # question_list는 페이징 객체(page_obj)
    # context = {'question_list': question_list}
    # #포장작업? 키값이 넘어간다.
    # # 'question_list' 이 templates\pybo 로 넘어간다.

    return render(request, 'pybo/question_list.html', context)
    #render(요청에 대한것과, 받는 곳, 보낼거(위에서 포장한거)) 새로운 페이지 요청
    #게시판을 사용할거다.


def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)
    #question_id 와 같이 넘어가야 질문에 대한 답변을 볼 수 있을듯

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <!-- 한글로 만들어짐-->
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- 표준언어 규약-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>어지럽다 어지러워</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<h1> 이건 기본입니다. </h1>

<!-- 네비게이션바 -->
{% include "navbar.html" %}


{% block contents %}

{% endblock %}


{% block content %}
<h1> 이건 추가된 텍스트 입니다.</h1>
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- Bootstrap JS
js는 기능이라고 보면 되나? -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>


{% comment %} body 엘리먼트 안의 {% block content %} 와 {% endblock %} 템플릿 태그는 base.html을 
상속한 템플릿에서 개별적으로 구현해야 하는 영역이 된다. {% endcomment %}

mysite/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

mysite/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">

                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    <!-- url에 common을 추가했잔아 그럼 그쪽으로 이동하자고-->
                    {% endif %}
                   
                </li>
                <li>
                    {% if user.is_anonymous %}
                    <!-- 로그인을 하지 않았다면,-->
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>