mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
# from pybo import views
# views안에 있는 함수들을 효율적으로 관리하기 위해
from pybo.views import base_views

#from pybo import views 너 대신에 위에 include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('pybo/', views.index),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    #로그인, 로그아웃을 위한 common을 등록
    # path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('', base_views.index, name='index'), # '/' 에 해당되는 path
]



#시작

mysite/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

from . import views

app_name = "pybo"
#pybo폴더가 하나이상일 경우 구분해주기 위함

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('<int:question_id>/', views.detail, name='detail'),
#     # path('<int:question_index>/', views.detail2),
#     # int:question_id >> 질문에 해당하는 번호
#     path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
#     path('question/create/', views.question_create, name='question_create'),
#     path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
#     path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
#     path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
#     path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    
# ]


urlpatterns = [
     # base_views.py
     path('',
          base_views.index, name='index'),
     path('<int:question_id>/',
          base_views.detail, name='detail'),

     # question_views.py
     path('question/create/',
          question_views.question_create, name='question_create'),
     path('question/modify/<int:question_id>/',
          question_views.question_modify, name='question_modify'),
     path('question/delete/<int:question_id>/',
          question_views.question_delete, name='question_delete'),

     # answer_views.py
     path('answer/create/<int:question_id>/',
          answer_views.answer_create, name='answer_create'),
     path('answer/modify/<int:answer_id>/',
          answer_views.answer_modify, name='answer_modify'),
     path('answer/delete/<int:answer_id>/',
          answer_views.answer_delete, name='answer_delete'),


     path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
     path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]



# 새로운 url을 여기서 등록
#

mysite/pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Question(models.Model):                       #테이블이름
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    # on_delete=models.CASCADE는 계정이 삭제되면 이 계정이 작성한 질문을 모두 삭제하라는 의미이다.
    # voter와 User가 겹치기 때문에 구분 필요! 
    subject = models.CharField(max_length=200)      #행이름 = models.어떤 타입로 작성할지(Char, tesxt)(추가속성)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    # null, 빈칸 허용
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가
    # N:N 관계 허용, author와 User가 겹치기 때문에 구분필요!


    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')



#수정은 여기서 가능.

mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):  #임의의 클래스 이름을 붙여 폼 작성을 해준다.
    class Meta: #오버라이딩 된 meta
        model = Question  # 사용할 모델-> 어떠한 데이터베이스 테이블을 지정할건지
        fields = ['subject', 'content']  # -> 직접입력할 부분만 지정
        # QuestionForm에서 사용할 Question 모델의 속성
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'cols':1, 'background-color': 'green', 'placeholder':'질문상세를 입력해주세요.'}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
    
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        lable = {
            'content' : '답변내용',
        }

#폼은 쉽게 말해 페이지 요청시 전달되는 파라미터들을 쉽게 관리하기 위해 사용하는 클래스이다.
#모델 폼은 이너 클래스인 Meta 클래스가 반드시 필요하다. 
# Meta 클래스에는 사용할 모델과 모델의 속성을 적어야 한다.

mysite/pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer




@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # #question = get_object_or_404(Answer, pk=answer_id)
    # #데이터 베이스
    # answer = Answer(question = question, content = request.POST.get('content'), create_date = timezone.now())
    # # question_detail에서 tecxtarea에 있는 contetn
    # answer.save()

    # return redirect('pybo:detail', question_id=question.id)
    # #현재 페이지에 머물고 싶다 ->redirect 기존에 있던 내용을 유지
    # # 결국 def detail() 로 넘어가는거임....
    if request.method == "POST":   # 답변이 있다면,
        form = AnswerForm(request.POST)  
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            # 외래키 내용 넣어주기
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=question.id), answer.id))
        
            # redirect 질문 상세페이지에 머무르기
    else:
        # return HttpResponseNotAllowed('Only POST is possible.')
        # 위 방식대로 하면 에러 405와 마주한다 이유는 Get방식으로 받아 들여서!!!!
        # get방식을 허용하지 않겠다  -> 무조건 내용을 넣어라
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)



@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)




@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id), answer.id))

mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from ..models import Question




def index(request):
    page = request.GET.get('page', '1') #페이지
    kw = request.GET.get('kw', '')  # 검색어
    # page = request.GET.get('page', '1')은 http://localhost:8000/pybo/?page=1 
    # 처럼 GET 방식으로 호출된 URL에서 page값을 가져올 때 사용한다. 
    # 만약 http://localhost:8000/pybo/ 처럼 page값 없이 호출된 경우에는 디폴트로 1이라는 값을 설정한다.
    question_list = Question.objects.order_by('-create_date')
    #order_by('-create_date')  create_date의 역순으로

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
            # subject__icontains=kw의 의미는 제목에 kw 문자열이 포함되었는지를 의미한다.
            # 대소문자 가리지 않고 찾아준다.
        ).distinct()

    paginator = Paginator(question_list, 10) #페이지 하나당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    # 요청된 페이지(page)에 해당되는 페이징 객체(page_obj)를 생성했다. 이렇게 하면 장고 
    # 내부적으로는 데이터 전체를 조회하지 않고 해당 페이지의 데이터만 조회하도록 쿼리가 변경된다.

    context = {'question_list' : page_obj, 'page': page, 'kw': kw} # question_list는 페이징 객체(page_obj)
    # context = {'question_list': question_list}
    # #포장작업? 키값이 넘어간다.
    # # 'question_list' 이 templates\pybo 로 넘어간다.

    return render(request, 'pybo/question_list.html', context)
    #render(요청에 대한것과, 받는 곳, 보낼거(위에서 포장한거)) 새로운 페이지 요청
    #게시판을 사용할거다.


def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)
    #question_id 와 같이 넘어가야 질문에 대한 답변을 볼 수 있을듯

mysite/pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():  # 폼이 유효하다면
            question = form.save(commit=False)  # 임시 저장하여 question 객체를 리턴받는다.
            question.author = request.user  # author 속성에 로그인 계정 저장
            # question.subject = "이걸로 채워지나?" 를 쓰면 덮어씌어진다.
            question.create_date = timezone.now()  # 실제 저장을 위해 작성일시를 설정한다.
            question.save()  # 데이터를 실제로 저장한다.
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)
# render 함수에 전달한 {'form': form}은 템플릿에서 질문 등록시 사용할 폼 엘리먼트를 생성할 때 쓰인다.
#request.POST를 인수로 QuestionForm을 생성할 경우에는 request.POST에 담긴 subject, content 값이 
# QuestionForm의 subject, content 속성에 자동으로 저장되어 객체가 생성된다.


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        #로그인한 사람과 글쓴이가 다르다면, 오류메시지 출력
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        # instance를 기준으로 QuestionForm을 생성하지만 request.POST의 값으로 덮어쓰라는 의미이다
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
        #폼 생성시 이처럼 instance 값을 지정하면 폼의 속성 값이 instance의 값으로 채워진다. 
        # 따라서 질문을 수정하는 화면에서 제목과 내용이 채워진 채로 보일 것이다.

    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)
    # 질문하기 수정하기는 질문등록하기와 폼이 동일하기때문   


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')



@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
        # voter는 여러사람을 추가할 수 있는 ManyToManyField이므로
        # question.voter.add(request.user) 처럼 add 함수를 사용하여 추천인을 추가한다.
    return redirect('pybo:detail', question_id=question.id)

mysite/templates/pybo/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
     
</head>
<body>
    {% extends 'base.html' %}
    {% load pybo_filter %}
    {% block content %} 
    <div class="container my-3">
        <!-- 수정 권한 오류 message 표시 -->
        {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
        </div>
        {% endif %}
        <!-- 질문 -->
        <h2 class="border-bottom py-2 ">{{ question.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" >{{ question.content|mark }}</div>
                <div class="d-flex justify-content-end">
                    {% if question.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge bg-light text-dark p-2text-start">
                        <div class="mb-2">{{ question.author.username }}</div>
                        <div>{{ question.create_date }}</div>
                    </div>
                </div>
                <!-- 수정일시 -->
                <div class="my-3">
                    <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id  %}"
                        class="recommend btn btn-sm btn-outline-secondary"> 추천
                        <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                    </a>
                    {% if request.user == question.author %}
                    <!-- 로그인한자와, 글쓴이가 동일할 경우-->
                    <a href="{% url 'pybo:question_modify' question.id  %}" 
                       class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                        data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                    <!-- 버튼을 눌렀을떄 바로 삭제하지 않고 확인을 한번 하려고 하기
                    때문에 href="javascript:void(0)"를 사용 -->
                    <!-- 삭제를 실행할 URL을 얻기 위해 data-uri 속성을 추가하고, 
                    <삭제> 버튼이 눌리는 이벤트를 확인할 수 있도록 class 속성에 "delete" 항목을 추가했다. -->
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- 답변 -->
        <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
        {% for answer in question.answer_set.all %}
        <a id="answer_{{ answer.id }}"></a>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line;">{{ answer.content|mark }}</div>
                <div class="d-flex justify-content-end">
                    {% if answer.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge bg-light text-dark p-2text-start">
                        <div class="mb-2">{{ answer.author.username }}</div>
                        <div>{{ answer.create_date }}</div>
                    </div>
                </div>
                <div class="my-3">
                    <a href="javascript:void(0)" data-uri="{% url 'pybo:answer_vote' answer.id  %}"
                        class="recommend btn btn-sm btn-outline-secondary"> 추천
                        <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                    </a>
                    {% if request.user == answer.author %}
                    <a href="{% url 'pybo:answer_modify' answer.id  %}" 
                       class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary "
                        data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}




        <!-- 답변 등록하기 -->
        <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
            {% csrf_token %}
            <!-- 오류표시 Start -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
            {% endfor %}
            </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="mb-3">
                <label for="content" class="form-label">답변내용</label>
                <textarea {% if not user.is_authenticated %} disabled {% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
                <!--  if not user.is_authenticated  태그는 현재 사용자가 로그아웃 상태인지를 체크하는 태그이다. -->
            </div>
            <input type="submit" value="답변등록" class="btn btn-primary">
        </form>
    </div>

    {% endblock %}
    {% block script %}
        <script type='text/javascript'>
        const delete_elements = document.getElementsByClassName("delete");
        Array.from(delete_elements).forEach(function(element) {
            element.addEventListener('click', function() {
                if(confirm("정말로 삭제하시겠습니까?")) {
                    location.href = this.dataset.uri;
                };
            });
        });

        const recommend_elements = document.getElementsByClassName("recommend");
        Array.from(recommend_elements).forEach(function(element) {
            element.addEventListener('click', function() {
                if(confirm("정말로 추천하시겠습니까?")) {
                    location.href = this.dataset.uri;
                };
            });
        });
        </script>
    {% endblock %}
</body>
</html>

mysite/templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">무엇이 궁금하신가요?</h5>
    <form method="post">
    <!-- <form method="post" action="{% url 'pybo:question_create' %}"> -->
        {% csrf_token %}
            <!-- 오류표시 Start -->
            {% if form.errors %}
            <!-- 데이터베이스 규칙위반시 -->
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <!-- 에러명 -->
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    <!-- 에러설명  -->
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="mb-3">
                <label for="subject" class="form-label">제목</label>
                <input type="text" class="form-control" name="subject" id="subject"
                        value="{{ form.subject.value | default_if_none:'' }}">
                        <!-- 한줄에 보이기위해 label과 input을 for과 id로 연결 -->
                        <!-- input의 name은 subject연결이름-->
                        <!-- subject 입력란에 내용르 입력하지 않으면 none이 들어가기때문에
                        none을 공백으로 바꿔준다.-->
            </div>
            <div class="mb-3">
                <label for="content" class="form-label">내용</label>
                <textarea class="form-control" name="content"
                            id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                            <!-- value의 값? -->
            </div>
    
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

<!--form 태그에 action 속성을 지정하지 않으면 
    호출한 대상한테 다시 보내준다.-->
<!-- 동일한 템플릿을 여러 기능에서 함께 사용할 경우에는 
    이처럼 form의 action 속성을 비워두는 트릭을 종종 사용한다.  -->

<!-- {{ form.as_p }} 는 forms.py 에 있는 걸 사용할수 있음?-->

mysite/templates/pybo/question_list.html
<!doctype html>
<html>
    <head>
        {% extends 'base.html' %}
        {% load pybo_filter %}
        {% block contents %} 
        <style>
            a {
                color : black;
                text-decoration : none;
                background-color: green;
            }
        </style>
    </head>
    <body>
        <div class="container my-3">
            <div class="row my-3">
                <div class="col-6">
                    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
                </div>
                <div class="col-6">
                    <div class="input-group">
                        <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                        <!-- 자바 스크립트에서 이 텍스트창에 입력된 값을 읽기 위해 다음처럼 id 속성을 추가한 점에 주목하자. -->
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table">

                <thead>
                    <tr class="text-center table-dark">
                        <th>번호</th>
                        <th style="width:50%">제목</th>
                        <th>글쓴이</th>
                        <th>작성일시</th>
                    </tr>
                </thead>

                <tbody>
                    {% if question_list %}              <!-- pybo/views.py에서 넘어온 question_list가 있다면-->
                        <!-- subject, id, content, c_d-->
                    {% for question in question_list %}
                    <tr class="text-center">
                        <!--<td>{{ forloop.counter }}</td> -->
                        <!-- <li><a href="/pybo/{{ question.id }}/">{{ question.subject }}</a></li> --> 
                        <td>
                            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 +1 -->
                            {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                        </td>
                        <td class="text-start">
                            <!-- "text-start"는 왼족 정렬-->
                            <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                        <!-- question.subject가 표기됨 {{ 객체 }} -->
                        <!-- question.id 는 질문 번호에 따라 넘어가는 질문이 달라짐-->
                        <!-- 여기서 question.id는 URL 매핑에 정의된 <int:question_id>에 전달해야 하는 값을 의미한다-->
                            {% if question.answer_set.count > 0 %}
                            <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                            <!-- 답변 갯수 표시-->
                            {% endif %}
                        </td>
                        <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
                        <td> {{ question.create_date }}</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colsan="4">질문이 없습니다.</td>
                    </tr>
                    
                    {% endif %}
                </tbody>
            </table>
            <!-- 페이징 시작-->
            <ul class="pagination justify-content-center">

                <!-- 이전페이지-->
                {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ question_list.previous_page_number }}"
                        href="javascript:void(0)">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif%}

                <!-- 페이지리스트 -->
                {% for page_number in question_list.paginator.page_range %}

                {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                <!-- 여기서 사용한 |add:-5, |add:5 는 템플릿 필터이다. 
                    |add:-5는 5만큼 빼라는 의미이고 |add:5는 5만큼 더하라는 의미이다.
                위 코드는 페이지 리스트가 현재 페이지 기준으로 좌우 5개씩 보이도록 만든다.-->
                {% if page_number == question_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" data-page="{{ page_number }}"
                    href="javascript:void(0)">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ page_number }}"
                    href="javascript:void(0)">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endif %}
                {% endfor %}

                <!--다음페이지-->
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ question_list.next_page_number }}"
                    href="javascript:void(0)">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif%}
            </ul>
            <!-- 페이징 처리 끝-->
            {% comment %} <a href="{% url 'pybo:question_create'%}" class="btn btn-primary"> 질문 등록하기</a> {% endcomment %}
            <!-- 상단으로 이동함 -->
            <!-- 부트스트랩의 btn btn-primary 클래스를 적용하면 버튼으로 보인다.  -->
            <!-- 이제 pybo:question_create 별칭에 해당되는 URL 매핑 규칙을 추가하자. -->
        </div>
        <form id="searchForm" method="get" action="{% url 'index' %}">
            <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
        {% endblock %}
        {% block script %}
        <script type='text/javascript'>
        const page_elements = document.getElementsByClassName("page-link");
        Array.from(page_elements).forEach(function(element) {
            element.addEventListener('click', function() {
                document.getElementById('page').value = this.dataset.page;
                document.getElementById('searchForm').submit();
            });
        });
        const btn_search = document.getElementById("btn_search");
        btn_search.addEventListener('click', function() {
            document.getElementById('kw').value = document.getElementById('search_kw').value;
            document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
            document.getElementById('searchForm').submit();
        });
        </script>
        {% endblock %}
    </body>

</html>